services:
  mysql:
    image: mysql:8.4
    container_name: wasteappfinal-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wasteappfinal
      MYSQL_USER: wasteuser
      MYSQL_PASSWORD: wastepass
    ports:
      - "3310:3306"
    volumes:
      - wasteappfinal_mysql_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: wasteappfinal-adminer
    restart: unless-stopped
    ports:
      - "8090:8080"

volumes:
  wasteappfinal_mysql_data:
